### ISSUE TITLE
Add additional inputs option for lupdate

### ISSUE THREAD

**Issue by AWorkingAlt** [qtproject/qt-labs-vstools#25] opened 2024-03-12 07:27 UTC
**Is your feature request related to a problem? Please describe.**
When generating translation files for multi-project solutions, it would be very useful to list multiple projects as source paths for the lupdate command.

**Describe the solution you'd like**
In **Project Properties -> Qt Translation -> lupdate** there should be a "additional sources" parameter. When the command resolves to `lupdate [options] [source-file|path|@lst-file]... -ts ts-files|@lst-file` the additional sources would be placed before the "-ts".

**Describe alternatives you've considered**
lupdate has the -I parameter for "include files" but these don't seem to work for including additionl sources.

**Comment by acdemiralp** [comment] 2024-03-20 23:20
Thank you very much for reporting the issue; it has been recorded in our public bug tracker, and all further updates will take place there. Here is the link: [QTVSADDINBUG-1185](https://bugreports.qt.io/browse/QTVSADDINBUG-1185)

Edit: I have attempted to replicate the problem. 

The latest version already supports calling lupdate on the whole solution:
![1](https://github.com/qt-labs/vstools/assets/6049621/18a85c00-4718-490e-83ed-01e8546e54dd)
However this creates separate translation files for each project, and will overwrite if translation files are shared between projects, which I believe is not what is desired.

Having a single translation file for the whole solution is possible using the command format mentioned in the issue, by prepending the AdditionalOptions parameter:
![2](https://github.com/qt-labs/vstools/assets/6049621/63ee764d-1395-46b9-9dac-10abf2cafe3d)
Here lupdate is called on project_1. The translation_1 comes from project_1, and translation_2 comes from project_2, which I believe solves the problem.

If none of these fit your requirement, please re-open the issue and describe the desired behavior further in the bug tracker.

**Comment by kaheimri** [comment] 2024-06-24 07:09
We were unable to reproduce the problem as described. Therefore, we are closing this issue as "Cannot reproduce." If you have additional information or steps to reproduce, please feel free to reopen the issue with those details. Issue: [QTVSADDINBUG-1185](https://bugreports.qt.io/browse/)

**Closed as completed** 2024-06-24 07:15 UTC
